### ISSUE TITLE
Electron version?

### ISSUE THREAD

**Issue by mpastell** [Ivshti/wcjs-prebuilt#1]
It would be useful to state the Electron version that can be used with the builds.

**Comment by Ivshti** [comment]
Sure, it's 0.29.2, you can see it in install.js. Wcjs gets CI prebuilts out for 0.29.2, 0.30.x, 0.31.x so you can probably change it.

**Comment by mpastell** [comment]
Thanks, maybe you should add it to Readme. It would be useful to see when browsing npm. Also maybe it would be good to remind windows users to use Electron ia32 build. I plan to use this to package for Mac and windows so thanks for making it available.

**Comment by Ivshti** [comment]
@mpastell closed with https://github.com/Ivshti/wcjs-prebuilt/commit/a8c6b37a6b059ef57423b6a1298afc5aebfa0936
