### ISSUE TITLE
Got "Error %1 is not a valid Win32 application"

### ISSUE THREAD

**Issue by Brantner** [Ivshti/wcjs-prebuilt#10]
Environment: Win7 x64, electron-prebuild 0.31.2

**Comment by jaruba** [comment]
are you using electron 0.31.2 x64?

**Comment by jaruba** [comment]
`WebChimera.js` requires electron 32bit on Windows, this is because there is no 64bit VLC for Windows. Mac and Linux use 64bit by default.

**Comment by jaruba** [comment]
You should also set the env variables when installing, for your case, I think it should be:

```
WCJS_PLATFORM=win32 WCJS_ARCH=ia32 WCJS_RUNTIME=electron45 npm install wcjs-prebuilt
```

**Comment by RSATom** [comment]
> WebChimera.js requires electron 32bit on Windows, this is because there is no 64bit VLC for Windows.

Small correction, there is 64 bit vlc on windows. 32 bit just used by default.

**Comment by RSATom** [comment]
> electron45

I believe this option was removed some time ago, so readme is outdated a little bit.

**Comment by Brantner** [comment]
I have replaced wcjs-prebuilt\bin\libvlc.dll and wcjs-prebuilt\bin\libvlccore.dll to the appropriate dlls from http://get.videolan.org/vlc/2.2.1/win64/vlc-2.2.1-win64.zip and this error was gone, but after that I faced with another problem:

``` javascript
        var renderer = require('./renderer.js'); //This is https://github.com/RSATom/wcjs-renderer with require to wcjs-prebuilt instead of webchimera.js 
        var player = renderer.init(document.getElementById("canvas"));
        player.playlist.add("test.mp4");
```

I receive -1 from the last statement without any exceptions or smth, and of course `player.play()` do nothing. How can I debug, what is the problem here?

**Comment by jaruba** [comment]
you need to use absolute paths and the `file:///` protocol, example of valid links:

```
file:///E:\\Videos\\test.mp4
```

or 

```
file:///E:/Videos/test.mp4
```

**Comment by RSATom** [comment]
@Brantner, you could use [DebugView](https://technet.microsoft.com/en-us/library/bb896647.aspx) to see debug messages on Windows.
To enable verbose debug mode you could use following:
`var player = renderer.init(document.getElementById("canvas", ["-vvv"]));`

**Comment by Brantner** [comment]
Thanks! It seems that WebChimera.js_electron_0.33.8_x64_win.zip was built for 32 bit version, so vlc x64 dlls was not properly initialized during startup (have no idea what is the problem, just saw a general error in DebugView: [4988] core libvlc error: No plugins found! Check your VLC installation.). 
After moving to 32bit electron and setting WCJS_ARCH=ia32 all issues was fixed.

**Comment by RSATom** [comment]
@Brantner, hm... I'll look what could be wrong. Thanks!

**Comment by RSATom** [comment]
@Ivshti, @jaruba, @luigiplr, did you try use `wcjs` x64?

**Comment by RSATom** [comment]
> I have replaced wcjs-prebuilt\bin\libvlc.dll and wcjs-prebuilt\bin\libvlccore.dll to the appropriate dlls from http://get.videolan.org/vlc/2.2.1/win64/vlc-2.2.1-win64.zip

@Brantner, maybe problem is you replaced only `libvlc.dll` and `libvlccore.dll` but didn't replace plugins? If yes, it's definitely should not work.

**Comment by luigiplr** [comment]
PR #13 should fix this.

**Comment by luigiplr** [comment]
@Brantner ??

**Comment by guidupuy** [comment]
#22 fixes the issue by fetching VLC prebuilt from the WebChimera repo, which includes both `x64` and `ia32` versions of VLC
