### ISSUE TITLE
VLC repo is wonky

### ISSUE THREAD

**Issue by Ivshti** [Ivshti/wcjs-prebuilt#15]
There are no releases that work apparently, I tried
darwin x64
mac x64
linux x64

So the latest version of this is kind of useless

**Comment by RSATom** [comment]
Do you mean `wcjs` x64 is broken on all platforms?

**Comment by RSATom** [comment]
Or do you talking about VLC nightlies?

**Comment by Ivshti** [comment]
I'm talking about the Magics vlc-prebuilt repos. Don't worry, it has nothing to do with wcjs itself, but with this module installing vlc-prebuilt @RSATom

**Comment by RSATom** [comment]
Uff...

**Comment by guidupuy** [comment]
#22 fixes this issue
