### ISSUE TITLE
No plugins found! Check your VLC installation.

### ISSUE THREAD

**Issue by Shaienn** [Ivshti/wcjs-prebuilt#16]
Hello. 
I have clean ubuntu with installed libvlc-dev. 
I create application with `nw.js 0.12.3`. 

In command line:
`WCJS_PLATFORM=linux` 
`WCJS_ARCH=x64` 
`WCJS_RUNTIME=nw.js` 
`npm install wcjs-prebuilt`

Add: 
`var wcjs = require("wcjs-prebuilt");`
`App.vlc = wcjs.createPlayer();`

And run application. In console i see 

> main libvlc error: No plugins found! Check your VLC installation.

As i understand, vlc did not found plugins directory. How to fix it? 

Thanks.

**Comment by RSATom** [comment]
try install `vlc-nox`

**Comment by guidupuy** [comment]
@Shaienn any news? Can the issue be considered fixed?

**Comment by RSATom** [comment]
too long time without answer...
