### ISSUE TITLE
No download candidate availale

### ISSUE THREAD

**Issue by lamo2k123** [Ivshti/wcjs-prebuilt#19]
WCJS_RUNTIME=electron npm install wcjs-prebuilt

return out:
Runtime detected as: electron 
Arch: x64
No download candidate availale
undefined

**Comment by lamo2k123** [comment]
wcjs-prebuilt - 2.0.8

**Comment by lamo2k123** [comment]
npm 3.7.5
node v5.6.0

**Comment by RSATom** [comment]
Patch welcome! Until that I recommend you use prebuilts directly from https://github.com/RSATom/WebChimera.js/releases

**Comment by guidupuy** [comment]
#22 should fix the issue
