### ISSUE TITLE
Update wcjs-prebuilt to work with the current version of Electron

### ISSUE THREAD

**Issue by dcposch** [Ivshti/wcjs-prebuilt#20]
It would be sweet if it supported Electron `0.37.5`

**Comment by Ivshti** [comment]
what's preventing it from supporting it at the moment?

I think it's that webchimera.js does not include electron 0.37.5 build in it's Releases tab

**Comment by RSATom** [comment]
I've forced latest version rebuild on CI. Required version should be available soon on Releases page of `WebChimera.js`.
