### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by jaruba** [Ivshti/wcjs-prebuilt#25]
Seems to work (for me at least). @Ivshti can you release and publish it to NPM?

**Comment by Ivshti** [comment]
Sure, doing it

**Comment by Ivshti** [comment]
I can give you npm access too

**Comment by Ivshti** [comment]
What's your username?
otherwise I published

**Comment by jaruba** [comment]
https://staging.npmjs.com/~jaruba

**Comment by Ivshti** [comment]
Ivo-MacBook-Pro:wcjs-prebuilt ivogeorgiev$ npm owner add jaruba
- jaruba (wcjs-prebuilt)

**Comment by jaruba** [comment]
thanks :)
