### ISSUE TITLE
Adding wcjs-prebuilt configuration parameters in package.json has no effect

### ISSUE THREAD

**Issue by KiresMA** [Ivshti/wcjs-prebuilt#35]
Hello,
I'm trying to set wcjs-prebuilt parameters in package.json, but it just ignores it. Here is what I'm trying to add:
"wcjs-prebuilt": {
  "arch": "ia32",
  "runtime":  "nw",
  "runtimeVersion":  "v0.16.1",
  "version": "v0.2.6"
}
But during npm install it downloads electron version anyway, so it just can not find those parameters and takes the default ones.

**Comment by Ivshti** [comment]
@jaruba @RSATom are you aware of such behaviour being expected?

**Comment by RSATom** [comment]
@Ivshti, I don't use `wcjs-prebuilt` in any way.

**Comment by Ivshti** [comment]
@KiresMA any insight as to why you closed it?

**Comment by KiresMA** [comment]
@Ivshti I understood this sentence in a way that it should work this way and there is nothing unusual in this problem.
"are you aware of such behaviour being expected?"

I have several package.json files on different folder levels, so I placed one more package.json with wcjs-prebuilt parameters I need in the root of my project and it works now.
Sorry for not mentioning it when I closed the issue
