### ISSUE TITLE
packaging into windows installer has problems with the depth of `node_modules`

### ISSUE THREAD

**Issue by erikyuzwa** [Ivshti/wcjs-prebuilt#39]
I love this library, and it handles my Electron apps video requirements very nicely. 🙇 

The one trouble I'm running into is trying to put together an installer for Windows. I've tried using NSIS, Squirrel, and just about any Electron based installer I can find on NPM.

The problem they all seem to encounter is running into `MAX_PATH` or related issues with the depth of the `node_modules` folders of each dependency. 

Any tips or advice from anyone who's been able to build an installer? thanks!

**Comment by erikyuzwa** [comment]
omfg - well it turns out the entire `node_modules` folder tree can be ignored during the installer creation and things seem to still all work. 🎸

**Comment by jaruba** [comment]
Lol, that's a windows specific issue, it has nothing to do with this module or any other particular module.

If you still run into issues with this in the future, look into flattening your `node_modules` folder. My personal recommendation, and something that I've successfully used in the past is [flatten_packages](https://www.npmjs.com/package/flatten-packages).

**Comment by erikyuzwa** [comment]
thanks!
yes, I agree 100% that it wasn't a specific issue with `wcjs-prebuilt`. I was just getting a little desperate and reaching out to others creating an installer using this lib. 

Thanks for the `flatten_packages` suggestion. :+1:

**Comment by erikyuzwa** [comment]
Just as a future note to anyone stuck on the same configuration (maybe fixable by `yarn` sometime soon?)
My idea of ignoring `node_modules` from my packaging did **NOT** in fact work, but the `flatten_packages` suggestion was a lifesaver.

**Comment by jaruba** [comment]
@erikyuzwa ;)
