### ISSUE TITLE
unrecognized chunk FATAL error on Windows Platform on Electron

### ISSUE THREAD

**Issue by evidential** [Ivshti/wcjs-prebuilt#40]
I have WebChimera working perfectly with the pre-builts for Electron 1.3.3, 1.4.0 and 1.4.3 on OSX.

I have built my app in Electron for Windows X64 trying the pre-builts for Electron 1.3.3, 1.4.0 and 1.4.3 but the video fails at the same point in the logs with an 'unrecognized chunk FATAL' error. This has happened with local files, and different types of network files which all play on the OSX version.

The logs from the Electron console are as follows:

index.html:11 VLC media player - 2.2.4 Weatherwax
index.html:11 Copyright © 1996-2016 the VideoLAN team
index.html:11 revision 2.2.4-0-g888b7e89
index.html:11 configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-twolame' '--enable-quicktime' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-x264' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--disable-sdl' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=x86_64-w64-mingw32' 'host_alias=x86_64-w64-mingw32'
index.html:11 option vmem-chroma does not exist
index.html:11 option vmem-width does not exist
index.html:11 option vmem-height does not exist
index.html:11 option vmem-pitch does not exist
index.html:11 option marq-color does not exist
index.html:11 option marq-opacity does not exist
index.html:11 option marq-position does not exist
index.html:11 option marq-refresh does not exist
index.html:11 option marq-size does not exist
index.html:11 option marq-timeout does not exist
index.html:11 option marq-x does not exist
index.html:11 option marq-y does not exist
index.html:11 option logo-x does not exist
index.html:11 option logo-y does not exist
index.html:11 option logo-delay does not exist
index.html:11 option logo-repeat does not exist
index.html:11 option logo-opacity does not exist
index.html:11 option logo-position does not exist
index.html:11 option contrast does not exist
index.html:11 option brightness does not exist
index.html:11 option hue does not exist
index.html:11 option saturation does not exist
index.html:11 option gamma does not exist
index.html:11 option amem-format does not exist
index.html:11 option amem-rate does not exist
index.html:11 option amem-channels does not exist
index.html:11 creating audio output
index.html:11 looking for audio output module matching "any": 0 candidates
index.html:11 no audio output modules
index.html:11 no suitable audio output module
index.html:11 Creating an input for 'http://video.webmfiles.org/big-buck-bunny_trailer.webm'
index.html:11 using timeshift granularity of 50 MiB, in path 'C:\Users\ODonnell\AppData\Local\Temp'
index.html:11 `http://video.webmfiles.org/big-buck-bunny_trailer.webm' gives access`http' demux `' path`video.webmfiles.org/big-buck-bunny_trailer.webm'
index.html:11 specified demux `any'
index.html:11 creating demux: access='http' demux='any' location='video.webmfiles.org/big-buck-bunny_trailer.webm' file='\\video.webmfiles.org\big-buck-bunny_trailer.webm'
index.html:11 looking for access_demux module matching "http": 4 candidates
index.html:11 no access_demux modules matched
index.html:11 creating access 'http' location='video.webmfiles.org/big-buck-bunny_trailer.webm', path='\\video.webmfiles.org\big-buck-bunny_trailer.webm'
index.html:11 looking for access module matching "http": 6 candidates
index.html:11 option http-proxy does not exist
index.html:11 net: connecting to video.webmfiles.org port 80
index.html:11 connection succeeded (socket = 1124)
index.html:11 HTTP reply 'HTTP/1.1 200 OK'
index.html:11 content-length = 2165175
index.html:11 unrecognized chunk FATAL (0x451a)
index.html:11 complete header size=0
index.html:11 header size == 0
index.html:11 no access modules matched
index.html:11 open of`http://video.webmfiles.org/big-buck-bunny_trailer.webm' failed
index.html:11 Your input can't be opened
index.html:11 VLC is unable to open the MRL 'http://video.webmfiles.org/big-buck-bunny_trailer.webm'. Check the log for details.

This has happened using Windows 8 through Parallels on  aMac and also natively on a Windows PC.

**Comment by RSATom** [comment]
For me it looks like libvlc can't find plugins.
Please read this: https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by evidential** [comment]
Thanks RSATom

I've got it working now.

Because I was using an .asar archive I was using wcjs-prebuilt outside of the archive and changing the plugins path in Electron's main.js file and path to wcjs-prebuilt accordingly. Must have been an issue somewhere with these paths.

Stripping everything back to use an app directory and with wcjs-prebuilt in the normal node_modules directory it works fine.

Definitely an issue with my setup and not a problem with wcjs-prebuilt (which is absolutely fantastic BTW!)
