### ISSUE TITLE
cannot download WebChimera.js_v0.2.4_electron_v0.37.8_VLC_v2.2.2_x64_osx.tar.gz

### ISSUE THREAD

**Issue by virskor** [Ivshti/wcjs-prebuilt#43]
cannot download WebChimera.js_v0.2.4_electron_v0.37.8_VLC_v2.2.2_x64_osx.tar.gz

**Comment by RSATom** [comment]
WebChimera.js is not supported anymore.

**Comment by RSATom** [comment]
If you still need it - you will have to build it yourself.
