### ISSUE TITLE
VLC prebuilt is not static for linux

### ISSUE THREAD

**Issue by Ivshti** [Ivshti/wcjs-prebuilt#5]
Currently, the VLC prebuilt for linux is not static, which means it depends on libav, and some other less famous libraries.

The solution would be use the VLC "Contrib" method for static building, but it seems awfully error prone.

**Comment by Ivshti** [comment]
@jaruba static builds are shit for VLC, they do not work, as I suspected, since everybody in the linux community considers static builds to be the devil.

I fixed 10-15 compilation errors and hit a rock in the end with VLC static build.

I am ruling this out - the best solution would be to ship our apps in _.deb/_rpm and have libav / etc as deps.

**Comment by RSATom** [comment]
> I am ruling this out - the best solution would be to ship our apps in .deb/rpm and have libav / etc as deps.

+1
or use ppa

**Comment by jaruba** [comment]
@Ivshti yeah, i looked into the matter myself too, the best solution i found was to package as deb that also triggers a install script, in the script i should add `apt-get install` for the required libs.

The dependency list is pretty big though.. https://wiki.videolan.org/Contrib_Status

It seems to have different dependencies if it's Ubuntu or Fedora though...

**Comment by RSATom** [comment]
apt-get manage dependencies itself, so it's enough just depend from vlc itself

**Comment by Ivshti** [comment]
@jaruba as @RSATom pointed out, when you're installing a deb in Ubuntu or another *.deb-based distro, it should handle deps by itself. Same for rpm.
