### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by heartnetkung** [Ivshti/wcjs-prebuilt#6]
[TypeError: Cannot read property 'platform of undefined']
This is due to the commit "1b7d07dd93585a68cfc1ecedf4b2ee6b63a84895"

To fix this, see
https://github.com/heartnetkung/wcjs-prebuilt/commit/9337003c812460967bafd5d103a45f36d5791987

**Comment by jaruba** [comment]
@Ivshti your fast.. :))

**Comment by Ivshti** [comment]
Thanks @heartnetkung , it's now fixed

I'm thinking of reverting the commit however since I'm using env variables

bad @luigiplr  :D

Seriously though, we should at least bump versions when making breaking changes

**Comment by RSATom** [comment]
Even if we are able use settings from `package.json` env variables still have a meaning...

**Comment by Ivshti** [comment]
Yep, definitely, env variables are always useful.

**Comment by heartnetkung** [comment]
btw u have a typo :)

``` js
//aquiring > acquiring
console.log('Aquiring:', downloadObject.name);
```

**Comment by jaruba** [comment]
> btw u have a typo :)

sounds like the work of @luigiplr ..

@heartnetkung it's not his fault, he's _italian_..

lol

**Comment by Ivshti** [comment]
@jaruba he makes great pizza

Seriously though, I'm vetoing this discussion :D

**Comment by luigiplr** [comment]
:pizza: :dancer: :+1:
