### ISSUE TITLE
Not enough game of thrones.

### ISSUE THREAD

**Issue by luigiplr** [Ivshti/wcjs-prebuilt#9]
Refer to title.

**Comment by RSATom** [comment]
It's not enough game of thrones even in games of thrones... so it's by design.

**Comment by Ivshti** [comment]
@RSATom good point :D

**Comment by Ivshti** [comment]
Let's turn this issue into something serious and address the lack of screenshots in wcjs-prebuilt's page

**Comment by luigiplr** [comment]
@Ivshti lmao.

okay ill add some.
